apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: order-service
  template:
    metadata:
      labels:
        name: order-service
    spec:
      containers:
      - name: order-service-container
        image: trdevops/java-app:order-service
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: svc-order-service
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  type: NodePort
  selector:
    name: order-service
