apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: user-service
  template:
    metadata:
      labels:
        name: user-service
    spec:
      containers:
      - name: user-service-container
        image: trdevops/java-app:user-service
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: svc-user-service
spec:
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
  type: NodePort
  selector:
    name: user-service